stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - specific-hetzner
  only:
    - master
  script:
    - docker info
    - docker build --build-arg BACKEND_URL=https://app.rifgo.com --build-arg APP_ADDRESS=https://app.rifgo.com -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  tags:
    - specific-hetzner
  only:
    - master
  script:
    # restart web container #1
    - docker stop rifgo_spa_1 || true
    - docker container rm rifgo_spa_1 || true
    - docker run --name rifgo_spa_1 --env-file $PROD_ENV -d -p 127.0.0.1:7010:80 --restart unless-stopped $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    # restart web container #2
    - docker stop rifgo_spa_2 || true
    - docker container rm rifgo_spa_2 || true
    - docker run --name rifgo_spa_2 --env-file $PROD_ENV -d -p 127.0.0.1:7011:80 --restart unless-stopped $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
